output   = "models"
wipe     = true
no-tests = true

[mysql]
  dbname    = "gomsx"
  host      = "database"
  port      = 3306
  user      = "gomsx"
  pass      = "gomsx"
  sslmode   = "false"
  blacklist = ["schema_migrations"]
