version: "3"

x-dbenv: &dbenv
  DB_USER: "gomsx_user"
  DB_PASSWORD: "gomsx_password"
  DB_HOST: "database"
  DB_NAME: "gomsx_development"
  DB_PORT: 3306

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    environment:
      ENV: "development"
      <<: *dbenv
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "5m"
    tty: true

  database:
    platform: linux/x86_64
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: root
      BIND-ADDRESS: 0.0.0.0
    command:
      [
          "mysqld",
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_bin",
      ]

  migration:
    build:
      context: ./tools/sqlmigrate
      dockerfile: Dockerfile
    volumes:
      - ./db/sqlmigrate.yml:/sqlmigrate/sqlmigrate.yml
      - ./db/migrations:/sqlmigrate/migrations
    environment:
      <<: *dbenv
    depends_on:
      - database
